# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkot Repository
      uses: actions/checkout@v3
    - name:   run fetch request 
      run: |
        export  FETCH_URL=${{ secrets.FETCH_URL }}
        echo $FETCH_URL
        python main.py > out.txt
        cat out.txt 
    - name: Commit files
      run: |
        #git config  user.email "ligu2006@gmail.com "
        #git config  user.name "lgweida"
        git add .
        git commit -m "add out.txt"
        git push
