# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkot Repository
      uses: actions/checkout@v3
    - name:   run fetch request 
      run: |
        # git rm out.txt
        # git commit -m " rm out.txt"
        # git push
        export  FETCH_URL=${{ secrets.FETCH_URL }}
        echo $FETCH_URL
        python main.py > out.txt
        cat out.txt 
    - name: Commit files
      run: |
        if [ -z "$(git status --short)" ]; then
          echo "Repo is clean, no need to push"
        else
          echo "Out.txt is changed push the repo"
          git add .
          git commit -m "update out.txt"
          git push
        fi
